version: '3'

services:
  php:
    image: php-custom:latest
    volumes:
      - ./:/application
    networks:
      - net

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - ./db-data:/var/lib/mysql:cached
    networks:
      - net

  nginx:
    image: nginx:alpine
    ports:
      - "8000:8000"
    volumes:
      - .cloud/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./:/application
    networks:
      - net

volumes:
  db-data:

networks:
  net:
